import type { LibrarySource } from "./model";

export const SAMPLE_FILES: readonly LibrarySource[] = [
  {
    id: "sample-test-cases",
    name: "Beneficiary test cases.xlsx",
    type: "XLSX",
    description:
      "Six test cases with priorities, expected results and execution status.",
    preview: { imageUrl: "/prototype-files/beneficiary-test-cases.png" },
    downloadUrl: "/prototype-files/beneficiary-test-cases.xlsx",
    origin: "page-local",
    status: "ready",
    isExample: true,
  },
  {
    id: "sample-underwriting",
    name: "Underwriting test rules.pdf",
    type: "PDF",
    description: "Decision boundaries, review triggers and expected outcomes.",
    preview: {
      imageUrl: "/prototype-files/underwriting-test-rules.png",
    },
    downloadUrl: "/prototype-files/underwriting-test-rules.pdf",
    origin: "page-local",
    status: "ready",
    isExample: true,
  },
  {
    id: "sample-beneficiary",
    name: "Beneficiary change workflow.docx",
    type: "DOCX",
    description: "Approval steps, allocation rules and audit evidence.",
    preview: {
      imageUrl: "/prototype-files/beneficiary-change-workflow.png",
    },
    downloadUrl: "/prototype-files/beneficiary-change-workflow.docx",
    origin: "page-local",
    status: "ready",
    isExample: true,
  },
  {
    id: "sample-exploratory",
    name: "Exploratory testing checklist.md",
    type: "MD",
    description: "Permissions, boundary values and recovery scenarios.",
    preview: {
      text: "# Exploratory testing checklist\n\nTAP sample file · Fictional application workflow\n\n## Explore beyond the happy path\n\nFollow the application from a saved draft to a reviewed decision. Change one assumption at a time and keep evidence of unexpected behavior.\n\n## Identity and access\n\n- Revoke a reviewer role while the review page is open.\n- Open a saved link after signing in as a different user.\n- Submit the same request from two browser tabs.\n\n## Boundaries and recovery\n\n- Try beneficiary allocations of 99%, 100% and 101%.\n- Interrupt the network immediately after confirmation.\n- Retry a timed-out submission and inspect the audit history.\n\n## Capture the discovery\n\nRecord the starting state, action, expected result and observed result. Attach the application reference so another tester can reproduce the issue.\n",
    },
    downloadUrl: "/prototype-files/exploratory-testing-checklist.md",
    origin: "page-local",
    status: "ready",
    isExample: true,
  },
  {
    id: "sample-log",
    name: "Beneficiary validation log.txt",
    type: "TXT",
    description: "A sample run with a duplicate-confirmation finding.",
    preview: {
      text: "TAP SAMPLE EXECUTION LOG\nFictional run: beneficiary allocation checks\nRun ID: sample-run-042\nEnvironment: prototype\n\n09:41:02  START  Open beneficiary change request\n09:41:04  PASS   Policyholder permission verified\n09:41:06  PASS   Allocation of 100% accepted\n09:41:09  PASS   Allocation of 99% rejected\n09:41:12  FAIL   Duplicate confirmation created two audit events\n09:41:13  INFO   Expected one event for the same request ID\n09:41:15  END    3 passed / 1 failed\n\nNext investigation\nRepeat confirmation after a simulated network timeout.\nCheck whether the same idempotency key is retained on retry.\n",
    },
    downloadUrl: "/prototype-files/beneficiary-validation-log.txt",
    origin: "page-local",
    status: "ready",
    isExample: true,
  },
  {
    id: "sample-slides",
    name: "Exploratory testing briefing.pptx",
    type: "PPTX",
    description: "Exploration goals, investigation steps and evidence.",
    origin: "page-local",
    status: "ready",
    isExample: true,
    downloadUrl: "/prototype-files/exploratory-testing-briefing.pptx",
    preview: {
      imageUrl: "/prototype-files/exploratory-testing-briefing.png",
    },
  },
  {
    id: "sample-csv",
    name: "Beneficiary test data.csv",
    type: "CSV",
    description: "Boundary values for data-driven allocation checks.",
    origin: "page-local",
    status: "ready",
    isExample: true,
    downloadUrl: "/prototype-files/beneficiary-test-data.csv",
    preview: {
      text: "case_id,allocation_percent,expected_result\nBEN-001,100,accepted\nBEN-002,99,rejected\nBEN-003,101,rejected\n",
    },
  },
  {
    id: "sample-json",
    name: "Beneficiary request.json",
    type: "JSON",
    description: "A request payload with two beneficiaries and allocations.",
    origin: "page-local",
    status: "ready",
    isExample: true,
    downloadUrl: "/prototype-files/beneficiary-request.json",
    preview: {
      text: '{\n  "sample": true,\n  "requestId": "sample-request-042",\n  "policyId": "sample-policy-001",\n  "beneficiaries": [\n    {\n      "reference": "sample-person-a",\n      "allocationPercent": 60\n    },\n    {\n      "reference": "sample-person-b",\n      "allocationPercent": 40\n    }\n  ],\n  "expectedStatus": "pending_review"\n}\n',
    },
  },
  {
    id: "sample-yaml",
    name: "Test run config.yaml",
    type: "YAML",
    description: "Retry settings and executable scenario inputs.",
    origin: "page-local",
    status: "ready",
    isExample: true,
    downloadUrl: "/prototype-files/test-run-config.yaml",
    preview: {
      text: "# TAP sample configuration\nname: beneficiary-allocation\nenvironment: prototype\nretry:\n  attempts: 2\n  retain_request_id: true\ncases:\n  - id: BEN-001\n    allocation_percent: 100\n    expected: accepted\n  - id: BEN-002\n    allocation_percent: 99\n    expected: rejected\n",
    },
  },
  {
    id: "sample-xml",
    name: "Beneficiary response.xml",
    type: "XML",
    description: "A service response with review and audit fields.",
    origin: "page-local",
    status: "ready",
    isExample: true,
    downloadUrl: "/prototype-files/beneficiary-response.xml",
    preview: {
      text: '<?xml version="1.0" encoding="UTF-8"?>\n<!-- TAP fictional response example -->\n<response>\n  <requestId>sample-request-042</requestId>\n  <status>pending_review</status>\n  <allocationTotal>100</allocationTotal>\n  <auditEventCount>1</auditEventCount>\n</response>\n',
    },
  },
  {
    id: "sample-html",
    name: "Sample test report.html",
    type: "HTML",
    description: "A browser-readable report of validation outcomes.",
    origin: "page-local",
    status: "ready",
    isExample: true,
    downloadUrl: "/prototype-files/sample-test-report.html",
    preview: {
      imageUrl: "/prototype-files/sample-test-report.png",
    },
  },
  {
    id: "sample-rtf",
    name: "Beneficiary change workflow.rtf",
    type: "RTF",
    description: "Rich text version of the review workflow.",
    origin: "page-local",
    status: "ready",
    isExample: true,
    downloadUrl: "/prototype-files/beneficiary-change-workflow.rtf",
    preview: {
      imageUrl: "/prototype-files/beneficiary-change-workflow.png",
    },
  },
  {
    id: "sample-odt",
    name: "Beneficiary change workflow.odt",
    type: "ODT",
    description: "OpenDocument text version of the review workflow.",
    origin: "page-local",
    status: "ready",
    isExample: true,
    downloadUrl: "/prototype-files/beneficiary-change-workflow.odt",
    preview: {
      imageUrl: "/prototype-files/beneficiary-change-workflow.png",
    },
  },
  {
    id: "sample-doc",
    name: "Beneficiary change workflow.doc",
    type: "DOC",
    description: "Legacy Word version of the review workflow.",
    origin: "page-local",
    status: "ready",
    isExample: true,
    downloadUrl: "/prototype-files/beneficiary-change-workflow.doc",
    preview: {
      imageUrl: "/prototype-files/beneficiary-change-workflow.png",
    },
  },
  {
    id: "sample-ods",
    name: "Beneficiary test cases.ods",
    type: "ODS",
    description: "OpenDocument spreadsheet with six test scenarios.",
    origin: "page-local",
    status: "ready",
    isExample: true,
    downloadUrl: "/prototype-files/beneficiary-test-cases.ods",
    preview: {
      imageUrl: "/prototype-files/beneficiary-test-cases.png",
    },
  },
  {
    id: "sample-xls",
    name: "Beneficiary test cases.xls",
    type: "XLS",
    description: "Legacy Excel version of the test case matrix.",
    origin: "page-local",
    status: "ready",
    isExample: true,
    downloadUrl: "/prototype-files/beneficiary-test-cases.xls",
    preview: {
      imageUrl: "/prototype-files/beneficiary-test-cases.png",
    },
  },
  {
    id: "sample-odp",
    name: "Exploratory testing briefing.odp",
    type: "ODP",
    description: "OpenDocument presentation for the test briefing.",
    origin: "page-local",
    status: "ready",
    isExample: true,
    downloadUrl: "/prototype-files/exploratory-testing-briefing.odp",
    preview: {
      imageUrl: "/prototype-files/exploratory-testing-briefing.png",
    },
  },
  {
    id: "sample-ppt",
    name: "Exploratory testing briefing.ppt",
    type: "PPT",
    description: "Legacy PowerPoint version of the test briefing.",
    origin: "page-local",
    status: "ready",
    isExample: true,
    downloadUrl: "/prototype-files/exploratory-testing-briefing.ppt",
    preview: {
      imageUrl: "/prototype-files/exploratory-testing-briefing.png",
    },
  },
];
