// Isolated, route-mocked fixture data for the graph-overview/node-detail/
// edge-citation/highlight `ui:capture` screenshots (Task 10). Pure data, no
// network or React imports -- `ui-capture.spec.ts` feeds this straight into
// `page.route` handlers. No real customer/company names: all document and
// node labels describe a generic insurance underwriting/claims domain.

export const CAPTURE_SOURCE_GUIDE = {
  sourceId: "source-guide",
  documentId: "document-guide",
  documentRevisionId: "document-rev-guide",
  filename: "underwriting-guide.md",
  sourceName: "Underwriting guide",
};

export const CAPTURE_SOURCE_CLAIMS = {
  sourceId: "source-claims",
  documentId: "document-claims",
  documentRevisionId: "document-rev-claims",
  filename: "claims-handbook.md",
  sourceName: "Claims handbook",
};

// A second, not-yet-published revision of the claims handbook, distinct
// from `CAPTURE_SOURCE_CLAIMS.documentRevisionId` (the already-published
// revision backing the node detail's evidence) -- this is the one still
// being extracted, so `extractingRevisionIds` below never claims a
// published revision is also mid-extraction.
const CAPTURE_SOURCE_CLAIMS_PENDING_REVISION = "document-rev-claims-2";

// `GET .../knowledge/sources` -- two ready sources so the Library source
// filters and node detail "Open original" resolve to real source ids.
export const CAPTURE_KNOWLEDGE_SOURCES = {
  items: [
    {
      sourceId: CAPTURE_SOURCE_GUIDE.sourceId,
      name: CAPTURE_SOURCE_GUIDE.filename,
      documentCount: 1,
      readyCount: 1,
      failedCount: 0,
      createdAt: "2026-10-01T08:00:00Z",
    },
    {
      sourceId: CAPTURE_SOURCE_CLAIMS.sourceId,
      name: CAPTURE_SOURCE_CLAIMS.filename,
      documentCount: 1,
      readyCount: 1,
      failedCount: 0,
      createdAt: "2026-10-01T08:00:00Z",
    },
  ],
  nextCursor: null,
};

// `GET .../knowledge/published-sources` -- the corresponding two published
// revisions, resolving the graph's source filter and `sourceIdByRevisionId`.
export const CAPTURE_PUBLISHED_SOURCES = {
  items: [
    {
      sourceId: CAPTURE_SOURCE_GUIDE.sourceId,
      revisionId: CAPTURE_SOURCE_GUIDE.documentRevisionId,
      documentId: CAPTURE_SOURCE_GUIDE.documentId,
      filename: CAPTURE_SOURCE_GUIDE.filename,
      sourceName: CAPTURE_SOURCE_GUIDE.sourceName,
      partial: false,
      approvedItemCount: 10,
      inventoryItemCount: 10,
      expiresAt: null,
      publicationId: "publication-guide",
    },
    {
      sourceId: CAPTURE_SOURCE_CLAIMS.sourceId,
      revisionId: CAPTURE_SOURCE_CLAIMS.documentRevisionId,
      documentId: CAPTURE_SOURCE_CLAIMS.documentId,
      filename: CAPTURE_SOURCE_CLAIMS.filename,
      sourceName: CAPTURE_SOURCE_CLAIMS.sourceName,
      partial: false,
      approvedItemCount: 8,
      inventoryItemCount: 8,
      expiresAt: null,
      publicationId: "publication-claims",
    },
  ],
};

// `GET .../knowledge/graph/project` -- 3 communities (Underwriting 12,
// Claims 9, Servicing 6 = 27 nodes) and one source still being extracted
// (the claims-handbook revision), so the community column's extraction
// footer renders. Deviation from the task brief: `ProjectGraphView` has no
// `fragments` array in the generated schema -- "one EXTRACTING fragment" is
// modeled here via `extractingRevisionIds`, the field the UI actually reads
// (`CommunityList`'s footer, driven by `GraphOverview`'s
// `communitiesFooter`). `graphVersion` is the schema's required `number`,
// not the brief's literal `"capture-v1"` string -- that string is used
// below instead, where it belongs: the answer's edge-citation `graphVersion`
// (a free-text field on `GraphEndpointView`/`EdgeCitation`, separate from
// the project graph's numeric version).
export const CAPTURE_GRAPH_PROJECT = {
  graphVersion: 1,
  status: "READY",
  nodeCount: 27,
  edgeCount: 34,
  mergedAt: "2026-10-05T08:00:00Z",
  communities: [
    {
      communityId: "underwriting",
      label: "Underwriting",
      size: 12,
    },
    {
      communityId: "claims",
      label: "Claims",
      size: 9,
    },
    {
      communityId: "servicing",
      label: "Servicing",
      size: 6,
    },
  ],
  extractingRevisionIds: [CAPTURE_SOURCE_CLAIMS_PENDING_REVISION],
  partialRevisionIds: [],
};

// `GET .../knowledge/graph/overview` -- 27 nodes / 34 edges, degree 1-9.
// `ProjectGraphSubgraphView` has no `truncated` field either (that flag is
// computed client-side in `GraphOverview.tsx` from `nodes.length ===
// nodeLimit`); 27 nodes is well under the default `nodeLimit` (150), so the
// UI computes `truncated: false` on its own and "Load more" never renders.
export const CAPTURE_GRAPH_OVERVIEW = {
  graphVersion: 1,
  nodes: [
    {
      nodeId: "node-underwriting",
      nodeType: "PROCESS",
      label: "Underwriting review",
      canonicalKey: "underwriting",
      degree: 3,
      communityId: "underwriting",
      aliases: [],
    },
    {
      nodeId: "node-disclosure",
      nodeType: "REQUIREMENT",
      label: "Health disclosure",
      canonicalKey: "disclosure",
      degree: 8,
      communityId: "underwriting",
      aliases: ["Health declaration", "Medical disclosure"],
    },
    {
      nodeId: "node-approval",
      nodeType: "PROCESS",
      label: "Policy approval",
      canonicalKey: "approval",
      degree: 3,
      communityId: "underwriting",
      aliases: [],
    },
    {
      nodeId: "node-risk",
      nodeType: "PROCESS",
      label: "Risk assessment",
      canonicalKey: "risk",
      degree: 4,
      communityId: "underwriting",
      aliases: [],
    },
    {
      nodeId: "node-age-verification",
      nodeType: "REQUIREMENT",
      label: "Age verification",
      canonicalKey: "age-verification",
      degree: 1,
      communityId: "underwriting",
      aliases: [],
    },
    {
      nodeId: "node-premium-calc",
      nodeType: "PROCESS",
      label: "Premium calculation",
      canonicalKey: "premium-calc",
      degree: 2,
      communityId: "underwriting",
      aliases: [],
    },
    {
      nodeId: "node-medical-history",
      nodeType: "ENTITY",
      label: "Medical history",
      canonicalKey: "medical-history",
      degree: 1,
      communityId: "underwriting",
      aliases: [],
    },
    {
      nodeId: "node-smoker-status",
      nodeType: "ENTITY",
      label: "Smoker status",
      canonicalKey: "smoker-status",
      degree: 1,
      communityId: "underwriting",
      aliases: [],
    },
    {
      nodeId: "node-family-history",
      nodeType: "ENTITY",
      label: "Family history",
      canonicalKey: "family-history",
      degree: 1,
      communityId: "underwriting",
      aliases: [],
    },
    {
      nodeId: "node-underwriting-guideline",
      nodeType: "SYSTEM",
      label: "Underwriting guideline",
      canonicalKey: "underwriting-guideline",
      degree: 3,
      communityId: "underwriting",
      aliases: [],
    },
    {
      nodeId: "node-exclusion-clause",
      nodeType: "REQUIREMENT",
      label: "Exclusion clause",
      canonicalKey: "exclusion-clause",
      degree: 3,
      communityId: "underwriting",
      aliases: [],
    },
    {
      nodeId: "node-waiting-period",
      nodeType: "CONCEPT",
      label: "Waiting period",
      canonicalKey: "waiting-period",
      degree: 2,
      communityId: "underwriting",
      aliases: [],
    },
    {
      nodeId: "node-claims-handbook",
      nodeType: "SYSTEM",
      label: "Claims handbook",
      canonicalKey: "claims-handbook",
      degree: 4,
      communityId: "claims",
      aliases: [],
    },
    {
      nodeId: "node-claim-submission",
      nodeType: "PROCESS",
      label: "Claim submission",
      canonicalKey: "claim-submission",
      degree: 3,
      communityId: "claims",
      aliases: [],
    },
    {
      nodeId: "node-claim-assessment",
      nodeType: "PROCESS",
      label: "Claim assessment",
      canonicalKey: "claim-assessment",
      degree: 4,
      communityId: "claims",
      aliases: [],
    },
    {
      nodeId: "node-claim-approval",
      nodeType: "PROCESS",
      label: "Claim approval",
      canonicalKey: "claim-approval",
      degree: 3,
      communityId: "claims",
      aliases: [],
    },
    {
      nodeId: "node-claim-denial",
      nodeType: "PROCESS",
      label: "Claim denial",
      canonicalKey: "claim-denial",
      degree: 3,
      communityId: "claims",
      aliases: [],
    },
    {
      nodeId: "node-settlement-amount",
      nodeType: "CONCEPT",
      label: "Settlement amount",
      canonicalKey: "settlement-amount",
      degree: 1,
      communityId: "claims",
      aliases: [],
    },
    {
      nodeId: "node-fraud-check",
      nodeType: "PROCESS",
      label: "Fraud check",
      canonicalKey: "fraud-check",
      degree: 2,
      communityId: "claims",
      aliases: [],
    },
    {
      nodeId: "node-documentation-requirement",
      nodeType: "REQUIREMENT",
      label: "Documentation requirement",
      canonicalKey: "documentation-requirement",
      degree: 1,
      communityId: "claims",
      aliases: [],
    },
    {
      nodeId: "node-appeal-process",
      nodeType: "PROCESS",
      label: "Appeal process",
      canonicalKey: "appeal-process",
      degree: 2,
      communityId: "claims",
      aliases: [],
    },
    {
      nodeId: "node-policy-renewal",
      nodeType: "PROCESS",
      label: "Policy renewal",
      canonicalKey: "policy-renewal",
      degree: 4,
      communityId: "servicing",
      aliases: [],
    },
    {
      nodeId: "node-premium-payment",
      nodeType: "PROCESS",
      label: "Premium payment",
      canonicalKey: "premium-payment",
      degree: 3,
      communityId: "servicing",
      aliases: [],
    },
    {
      nodeId: "node-beneficiary-update",
      nodeType: "PROCESS",
      label: "Beneficiary update",
      canonicalKey: "beneficiary-update",
      degree: 1,
      communityId: "servicing",
      aliases: [],
    },
    {
      nodeId: "node-address-change",
      nodeType: "PROCESS",
      label: "Address change",
      canonicalKey: "address-change",
      degree: 1,
      communityId: "servicing",
      aliases: [],
    },
    {
      nodeId: "node-policy-lapse",
      nodeType: "CONCEPT",
      label: "Policy lapse",
      canonicalKey: "policy-lapse",
      degree: 2,
      communityId: "servicing",
      aliases: [],
    },
    {
      nodeId: "node-reinstatement",
      nodeType: "PROCESS",
      label: "Reinstatement",
      canonicalKey: "reinstatement",
      degree: 2,
      communityId: "servicing",
      aliases: [],
    },
  ],
  edges: [
    {
      edgeId: "e1",
      sourceNodeId: "node-underwriting",
      targetNodeId: "node-disclosure",
      relationType: "REQUIRES",
      relationLabel: "requires",
      confidence: 0.9,
      origin: "EXTRACTED",
    },
    {
      edgeId: "e2",
      sourceNodeId: "node-disclosure",
      targetNodeId: "node-risk",
      relationType: "REQUIRES",
      relationLabel: "requires",
      confidence: 0.9,
      origin: "EXTRACTED",
    },
    {
      edgeId: "e3",
      sourceNodeId: "node-disclosure",
      targetNodeId: "node-medical-history",
      relationType: "REQUIRES",
      relationLabel: "requires",
      confidence: 0.9,
      origin: "EXTRACTED",
    },
    {
      edgeId: "e4",
      sourceNodeId: "node-age-verification",
      targetNodeId: "node-disclosure",
      relationType: "REQUIRES",
      relationLabel: "requires",
      confidence: 0.9,
      origin: "EXTRACTED",
    },
    {
      edgeId: "e5",
      sourceNodeId: "node-disclosure",
      targetNodeId: "node-approval",
      relationType: "PRECEDES",
      relationLabel: "precedes",
      confidence: 0.9,
      origin: "EXTRACTED",
    },
    {
      edgeId: "e6",
      sourceNodeId: "node-disclosure",
      targetNodeId: "node-premium-calc",
      relationType: "PRECEDES",
      relationLabel: "precedes",
      confidence: 0.9,
      origin: "EXTRACTED",
    },
    {
      edgeId: "e7",
      sourceNodeId: "node-smoker-status",
      targetNodeId: "node-disclosure",
      relationType: "PRECEDES",
      relationLabel: "precedes",
      confidence: 0.9,
      origin: "EXTRACTED",
    },
    {
      edgeId: "e8",
      sourceNodeId: "node-disclosure",
      targetNodeId: "node-underwriting-guideline",
      relationType: "VALIDATED_BY",
      relationLabel: "validated by",
      confidence: 0.9,
      origin: "EXTRACTED",
    },
    {
      edgeId: "e9",
      sourceNodeId: "node-underwriting",
      targetNodeId: "node-risk",
      relationType: "USES",
      relationLabel: "uses",
      confidence: 0.9,
      origin: "EXTRACTED",
    },
    {
      edgeId: "e10",
      sourceNodeId: "node-risk",
      targetNodeId: "node-premium-calc",
      relationType: "TRIGGERS",
      relationLabel: "triggers",
      confidence: 0.9,
      origin: "EXTRACTED",
    },
    {
      edgeId: "e11",
      sourceNodeId: "node-family-history",
      targetNodeId: "node-risk",
      relationType: "APPLIES_TO",
      relationLabel: "applies to",
      confidence: 0.9,
      origin: "EXTRACTED",
    },
    {
      edgeId: "e12",
      sourceNodeId: "node-underwriting-guideline",
      targetNodeId: "node-exclusion-clause",
      relationType: "DEFINES",
      relationLabel: "defines",
      confidence: 0.9,
      origin: "EXTRACTED",
    },
    {
      edgeId: "e13",
      sourceNodeId: "node-exclusion-clause",
      targetNodeId: "node-waiting-period",
      relationType: "PART_OF",
      relationLabel: "part of",
      confidence: 0.9,
      origin: "EXTRACTED",
    },
    {
      edgeId: "e14",
      sourceNodeId: "node-approval",
      targetNodeId: "node-waiting-period",
      relationType: "TRIGGERS",
      relationLabel: "triggers",
      confidence: 0.9,
      origin: "EXTRACTED",
    },
    {
      edgeId: "e15",
      sourceNodeId: "node-underwriting",
      targetNodeId: "node-underwriting-guideline",
      relationType: "VALIDATED_BY",
      relationLabel: "validated by",
      confidence: 0.9,
      origin: "EXTRACTED",
    },
    {
      edgeId: "e16",
      sourceNodeId: "node-exclusion-clause",
      targetNodeId: "node-claim-denial",
      relationType: "RELATED_TO",
      relationLabel: "related to",
      confidence: 0.9,
      origin: "EXTRACTED",
    },
    {
      edgeId: "e17",
      sourceNodeId: "node-claims-handbook",
      targetNodeId: "node-claim-submission",
      relationType: "DEFINES",
      relationLabel: "defines",
      confidence: 0.9,
      origin: "EXTRACTED",
    },
    {
      edgeId: "e18",
      sourceNodeId: "node-claim-submission",
      targetNodeId: "node-claim-assessment",
      relationType: "PRECEDES",
      relationLabel: "precedes",
      confidence: 0.9,
      origin: "EXTRACTED",
    },
    {
      edgeId: "e19",
      sourceNodeId: "node-claim-assessment",
      targetNodeId: "node-fraud-check",
      relationType: "TRIGGERS",
      relationLabel: "triggers",
      confidence: 0.9,
      origin: "EXTRACTED",
    },
    {
      edgeId: "e20",
      sourceNodeId: "node-claim-assessment",
      targetNodeId: "node-claim-approval",
      relationType: "PRECEDES",
      relationLabel: "precedes",
      confidence: 0.9,
      origin: "EXTRACTED",
    },
    {
      edgeId: "e21",
      sourceNodeId: "node-claim-assessment",
      targetNodeId: "node-claim-denial",
      relationType: "PRECEDES",
      relationLabel: "precedes",
      confidence: 0.9,
      origin: "EXTRACTED",
    },
    {
      edgeId: "e22",
      sourceNodeId: "node-claim-denial",
      targetNodeId: "node-appeal-process",
      relationType: "TRIGGERS",
      relationLabel: "triggers",
      confidence: 0.9,
      origin: "EXTRACTED",
    },
    {
      edgeId: "e23",
      sourceNodeId: "node-claim-approval",
      targetNodeId: "node-settlement-amount",
      relationType: "TRIGGERS",
      relationLabel: "triggers",
      confidence: 0.9,
      origin: "EXTRACTED",
    },
    {
      edgeId: "e24",
      sourceNodeId: "node-claim-submission",
      targetNodeId: "node-documentation-requirement",
      relationType: "REQUIRES",
      relationLabel: "requires",
      confidence: 0.9,
      origin: "EXTRACTED",
    },
    {
      edgeId: "e25",
      sourceNodeId: "node-fraud-check",
      targetNodeId: "node-claims-handbook",
      relationType: "VALIDATED_BY",
      relationLabel: "validated by",
      confidence: 0.9,
      origin: "EXTRACTED",
    },
    {
      edgeId: "e26",
      sourceNodeId: "node-appeal-process",
      targetNodeId: "node-claims-handbook",
      relationType: "PART_OF",
      relationLabel: "part of",
      confidence: 0.9,
      origin: "EXTRACTED",
    },
    {
      edgeId: "e27",
      sourceNodeId: "node-policy-renewal",
      targetNodeId: "node-premium-payment",
      relationType: "REQUIRES",
      relationLabel: "requires",
      confidence: 0.9,
      origin: "EXTRACTED",
    },
    {
      edgeId: "e28",
      sourceNodeId: "node-premium-payment",
      targetNodeId: "node-policy-lapse",
      relationType: "TRIGGERS",
      relationLabel: "triggers",
      confidence: 0.9,
      origin: "EXTRACTED",
    },
    {
      edgeId: "e29",
      sourceNodeId: "node-policy-lapse",
      targetNodeId: "node-reinstatement",
      relationType: "PRECEDES",
      relationLabel: "precedes",
      confidence: 0.9,
      origin: "EXTRACTED",
    },
    {
      edgeId: "e30",
      sourceNodeId: "node-reinstatement",
      targetNodeId: "node-premium-payment",
      relationType: "REQUIRES",
      relationLabel: "requires",
      confidence: 0.9,
      origin: "EXTRACTED",
    },
    {
      edgeId: "e31",
      sourceNodeId: "node-beneficiary-update",
      targetNodeId: "node-policy-renewal",
      relationType: "RELATED_TO",
      relationLabel: "related to",
      confidence: 0.9,
      origin: "EXTRACTED",
    },
    {
      edgeId: "e32",
      sourceNodeId: "node-address-change",
      targetNodeId: "node-policy-renewal",
      relationType: "RELATED_TO",
      relationLabel: "related to",
      confidence: 0.9,
      origin: "EXTRACTED",
    },
    {
      edgeId: "e33",
      sourceNodeId: "node-approval",
      targetNodeId: "node-claims-handbook",
      relationType: "APPLIES_TO",
      relationLabel: "applies to",
      confidence: 0.9,
      origin: "EXTRACTED",
    },
    {
      edgeId: "e34",
      sourceNodeId: "node-claim-approval",
      targetNodeId: "node-policy-renewal",
      relationType: "APPLIES_TO",
      relationLabel: "applies to",
      confidence: 0.9,
      origin: "EXTRACTED",
    },
  ],
  evidence: [],
};

// `GET .../knowledge/graph/nodes/node-disclosure` -- "Health disclosure":
// 2 aliases, 2 source groups (one snippet-bearing evidence item each, from
// the two capture sources above), 3 relation groups totaling 8 edges
// (REQUIRES x4, PRECEDES x3, VALIDATED_BY x1). `e1` (Underwriting review
// --requires--> Health disclosure) is reused as the answer's edge citation
// in `CAPTURE_RELATION_CONVERSATION` below, so the node-detail and
// edge-citation captures are mutually consistent.
export const CAPTURE_GRAPH_NODE = {
  graphVersion: 1,
  node: {
    nodeId: "node-disclosure",
    nodeType: "REQUIREMENT",
    label: "Health disclosure",
    canonicalKey: "disclosure",
    degree: 8,
    communityId: "underwriting",
    aliases: ["Health declaration", "Medical disclosure"],
  },
  community: { communityId: "underwriting", label: "Underwriting", size: 12 },
  neighbors: [
    {
      nodeId: "node-age-verification",
      nodeType: "REQUIREMENT",
      label: "Age verification",
      canonicalKey: "age-verification",
      degree: 1,
      communityId: "underwriting",
      aliases: [],
    },
    {
      nodeId: "node-approval",
      nodeType: "PROCESS",
      label: "Policy approval",
      canonicalKey: "approval",
      degree: 3,
      communityId: "underwriting",
      aliases: [],
    },
    {
      nodeId: "node-medical-history",
      nodeType: "ENTITY",
      label: "Medical history",
      canonicalKey: "medical-history",
      degree: 1,
      communityId: "underwriting",
      aliases: [],
    },
    {
      nodeId: "node-premium-calc",
      nodeType: "PROCESS",
      label: "Premium calculation",
      canonicalKey: "premium-calc",
      degree: 2,
      communityId: "underwriting",
      aliases: [],
    },
    {
      nodeId: "node-risk",
      nodeType: "PROCESS",
      label: "Risk assessment",
      canonicalKey: "risk",
      degree: 4,
      communityId: "underwriting",
      aliases: [],
    },
    {
      nodeId: "node-smoker-status",
      nodeType: "ENTITY",
      label: "Smoker status",
      canonicalKey: "smoker-status",
      degree: 1,
      communityId: "underwriting",
      aliases: [],
    },
    {
      nodeId: "node-underwriting",
      nodeType: "PROCESS",
      label: "Underwriting review",
      canonicalKey: "underwriting",
      degree: 3,
      communityId: "underwriting",
      aliases: [],
    },
    {
      nodeId: "node-underwriting-guideline",
      nodeType: "SYSTEM",
      label: "Underwriting guideline",
      canonicalKey: "underwriting-guideline",
      degree: 3,
      communityId: "underwriting",
      aliases: [],
    },
  ],
  sources: [
    {
      sourceRevisionId: CAPTURE_SOURCE_GUIDE.documentRevisionId,
      documentRevisionId: CAPTURE_SOURCE_GUIDE.documentRevisionId,
      sourceName: CAPTURE_SOURCE_GUIDE.sourceName,
      evidence: [
        {
          chunkId: "chunk-guide-1",
          ownerId: "node-disclosure",
          ownerKind: "node",
          documentRevisionId: CAPTURE_SOURCE_GUIDE.documentRevisionId,
          sourceRevisionId: CAPTURE_SOURCE_GUIDE.documentRevisionId,
          snippet:
            "Health disclosure must be completed before underwriting review proceeds.",
          anchor: { type: "document" },
        },
      ],
    },
    {
      sourceRevisionId: CAPTURE_SOURCE_CLAIMS.documentRevisionId,
      documentRevisionId: CAPTURE_SOURCE_CLAIMS.documentRevisionId,
      sourceName: CAPTURE_SOURCE_CLAIMS.sourceName,
      evidence: [
        {
          chunkId: "chunk-claims-1",
          ownerId: "node-disclosure",
          ownerKind: "node",
          documentRevisionId: CAPTURE_SOURCE_CLAIMS.documentRevisionId,
          sourceRevisionId: CAPTURE_SOURCE_CLAIMS.documentRevisionId,
          snippet:
            "A claim referencing an undisclosed condition may be denied under the exclusion clause.",
          anchor: { type: "document" },
        },
      ],
    },
  ],
  relations: [
    {
      relationType: "REQUIRES",
      edges: [
        {
          edgeId: "e1",
          sourceNodeId: "node-underwriting",
          targetNodeId: "node-disclosure",
          relationType: "REQUIRES",
          relationLabel: "requires",
          confidence: 0.9,
          origin: "EXTRACTED",
        },
        {
          edgeId: "e2",
          sourceNodeId: "node-disclosure",
          targetNodeId: "node-risk",
          relationType: "REQUIRES",
          relationLabel: "requires",
          confidence: 0.9,
          origin: "EXTRACTED",
        },
        {
          edgeId: "e3",
          sourceNodeId: "node-disclosure",
          targetNodeId: "node-medical-history",
          relationType: "REQUIRES",
          relationLabel: "requires",
          confidence: 0.9,
          origin: "EXTRACTED",
        },
        {
          edgeId: "e4",
          sourceNodeId: "node-age-verification",
          targetNodeId: "node-disclosure",
          relationType: "REQUIRES",
          relationLabel: "requires",
          confidence: 0.9,
          origin: "EXTRACTED",
        },
      ],
    },
    {
      relationType: "PRECEDES",
      edges: [
        {
          edgeId: "e5",
          sourceNodeId: "node-disclosure",
          targetNodeId: "node-approval",
          relationType: "PRECEDES",
          relationLabel: "precedes",
          confidence: 0.9,
          origin: "EXTRACTED",
        },
        {
          edgeId: "e6",
          sourceNodeId: "node-disclosure",
          targetNodeId: "node-premium-calc",
          relationType: "PRECEDES",
          relationLabel: "precedes",
          confidence: 0.9,
          origin: "EXTRACTED",
        },
        {
          edgeId: "e7",
          sourceNodeId: "node-smoker-status",
          targetNodeId: "node-disclosure",
          relationType: "PRECEDES",
          relationLabel: "precedes",
          confidence: 0.9,
          origin: "EXTRACTED",
        },
      ],
    },
    {
      relationType: "VALIDATED_BY",
      edges: [
        {
          edgeId: "e8",
          sourceNodeId: "node-disclosure",
          targetNodeId: "node-underwriting-guideline",
          relationType: "VALIDATED_BY",
          relationLabel: "validated by",
          confidence: 0.9,
          origin: "EXTRACTED",
        },
      ],
    },
  ],
};

// `POST .../knowledge/graph/highlight` -- the "View in Library" target for
// the answer's edge citation (`e1`): 2 edges (the requested `e1`, plus `e5`
// as one-hop context: Health disclosure --precedes--> Policy approval) and
// their 3 endpoint nodes, so the "Highlighted path" region lists more than
// a single trivial relation.
export const CAPTURE_GRAPH_HIGHLIGHT = {
  graphVersion: 1,
  nodes: [
    {
      nodeId: "node-underwriting",
      nodeType: "PROCESS",
      label: "Underwriting review",
      canonicalKey: "underwriting",
      degree: 3,
      communityId: "underwriting",
      aliases: [],
    },
    {
      nodeId: "node-disclosure",
      nodeType: "REQUIREMENT",
      label: "Health disclosure",
      canonicalKey: "disclosure",
      degree: 8,
      communityId: "underwriting",
      aliases: ["Health declaration", "Medical disclosure"],
    },
    {
      nodeId: "node-approval",
      nodeType: "PROCESS",
      label: "Policy approval",
      canonicalKey: "approval",
      degree: 3,
      communityId: "underwriting",
      aliases: [],
    },
  ],
  edges: [
    {
      edgeId: "e1",
      sourceNodeId: "node-underwriting",
      targetNodeId: "node-disclosure",
      relationType: "REQUIRES",
      relationLabel: "requires",
      confidence: 0.9,
      origin: "EXTRACTED",
    },
    {
      edgeId: "e5",
      sourceNodeId: "node-disclosure",
      targetNodeId: "node-approval",
      relationType: "PRECEDES",
      relationLabel: "precedes",
      confidence: 0.9,
      origin: "EXTRACTED",
    },
  ],
  evidence: [],
};

// `GET /conversations` summary + `GET /conversations/{id}` detail + `GET
// /conversations/{id}/events` for a durable conversation whose single
// completed turn renders the chunk citation `[1]` and the edge citation
// `[R1]` side by side (`GroundedAnswer`'s dual numbering), so hovering
// `[R1]` and opening the evidence panel are both exercised. `traceId` is
// left `null` (falls back to `AnswerActivity`, not the trace panel --
// irrelevant here) but the `graph.context_ready` event still drives the
// answer summary line's relation count.
export const CAPTURE_RELATION_CONVERSATION = {
  summary: {
    conversationId: "conversation-relation",
    title: "Relation question",
    createdAt: "2026-10-05T08:00:00Z",
    updatedAt: "2026-10-05T08:00:01Z",
  },
  detail: {
    conversationId: "conversation-relation",
    title: "Relation question",
    createdAt: "2026-10-05T08:00:00Z",
    updatedAt: "2026-10-05T08:00:01Z",
    turns: [
      {
        turnId: "turn-relation",
        state: "completed",
        attempt: 1,
        traceId: null,
        inputSnapshotDigest: `sha256:${"a".repeat(64)}`,
        answerEvidenceSnapshotDigest: null,
        input: {
          message:
            "What must be completed before underwriting review approves the policy?",
          modelAlias: "qwen-plus",
          sourceRevisionIds: [CAPTURE_SOURCE_GUIDE.documentRevisionId],
          documentRevisionIds: [CAPTURE_SOURCE_GUIDE.documentRevisionId],
          resolvedResources: [
            {
              sourceId: CAPTURE_SOURCE_GUIDE.sourceId,
              documentId: CAPTURE_SOURCE_GUIDE.documentId,
              documentRevisionId: CAPTURE_SOURCE_GUIDE.documentRevisionId,
              sourceRevisionId: CAPTURE_SOURCE_GUIDE.documentRevisionId,
              label: CAPTURE_SOURCE_GUIDE.sourceName,
            },
          ],
          agentRevisionId: null,
          agentLabel: null,
          skillRevisionIds: [],
          skillLabels: [],
          insightsQueryId: null,
        },
      },
    ],
  },
  events: {
    items: [
      {
        eventId: "event-context",
        sequence: 1,
        turnId: "turn-relation",
        occurredAt: "2026-10-05T08:00:00Z",
        eventType: "context.assembled",
        payload: { contextSnapshotId: "context-capture", tokenCount: 512 },
      },
      {
        eventId: "event-graph",
        sequence: 2,
        turnId: "turn-relation",
        occurredAt: "2026-10-05T08:00:00Z",
        eventType: "graph.context_ready",
        payload: {
          status: "APPLIED",
          seedCount: 2,
          paths: [
            ["Underwriting review", "Health disclosure", "Policy approval"],
          ],
          relationCount: 2,
        },
      },
      {
        eventId: "event-completed",
        sequence: 3,
        turnId: "turn-relation",
        occurredAt: "2026-10-05T08:00:01Z",
        eventType: "turn.completed",
        payload: {
          answer: {
            traceId: null,
            queryPlanId: "plan-capture",
            contextSnapshotId: "context-capture",
            corpusVersion: "v1",
            retrievalProfileId: "quick",
            degradedMode: false,
            answer:
              "Health disclosure is required before underwriting review.\n\nPolicy approval follows automatically once the disclosure is verified.",
            abstained: false,
            claims: [
              {
                claimId: "claim-1",
                text: "Health disclosure is required before underwriting review.",
                answerStart: 0,
                answerEnd: 57,
                citationIds: ["c1", "e1"],
              },
              {
                claimId: "claim-2",
                text: "Policy approval follows automatically once the disclosure is verified.",
                answerStart: 59,
                answerEnd: 129,
                citationIds: ["e5"],
              },
            ],
            citations: [
              {
                citationId: "c1",
                evidenceLabel: "S1",
                chunkId: "chunk-guide-1",
                logicalChunkId: "logical-guide-1",
                source: {
                  sourceId: CAPTURE_SOURCE_GUIDE.sourceId,
                  sourceType: "document",
                  revisionKind: "blob_version",
                  revision: CAPTURE_SOURCE_GUIDE.documentRevisionId,
                  sourceContentHash: `sha256:${"a".repeat(64)}`,
                  anchor: {
                    type: "document",
                    headingPath: ["Health disclosure"],
                    page: 1,
                    bbox: null,
                    startOffset: 0,
                    endOffset: 72,
                  },
                },
                chunkContentHash: `sha256:${"b".repeat(64)}`,
                contentRole: "source",
                derivedFromChunkIds: null,
              },
              {
                citationId: "e1",
                evidenceLabel: "R1",
                chunkId: "chunk-guide-1",
                logicalChunkId: "logical-guide-1",
                source: {
                  sourceId: CAPTURE_SOURCE_GUIDE.sourceId,
                  sourceType: "document",
                  revisionKind: "blob_version",
                  revision: CAPTURE_SOURCE_GUIDE.documentRevisionId,
                  sourceContentHash: `sha256:${"a".repeat(64)}`,
                  anchor: {
                    type: "document",
                    headingPath: ["Health disclosure"],
                    page: 1,
                    bbox: null,
                    startOffset: 0,
                    endOffset: 72,
                  },
                },
                chunkContentHash: `sha256:${"b".repeat(64)}`,
                contentRole: "source",
                derivedFromChunkIds: null,
                kind: "edge",
                edge: {
                  edgeId: "e1",
                  graphVersion: "capture-v1",
                  subject: {
                    nodeId: "node-underwriting",
                    label: "Underwriting review",
                  },
                  object: {
                    nodeId: "node-disclosure",
                    label: "Health disclosure",
                  },
                  relationType: "REQUIRES",
                  relationLabel: "requires",
                },
              },
              {
                citationId: "e5",
                evidenceLabel: "R2",
                chunkId: "chunk-guide-2",
                logicalChunkId: "logical-guide-2",
                source: {
                  sourceId: CAPTURE_SOURCE_GUIDE.sourceId,
                  sourceType: "document",
                  revisionKind: "blob_version",
                  revision: CAPTURE_SOURCE_GUIDE.documentRevisionId,
                  sourceContentHash: `sha256:${"a".repeat(64)}`,
                  anchor: {
                    type: "document",
                    headingPath: ["Policy approval"],
                    page: 1,
                    bbox: null,
                    startOffset: 72,
                    endOffset: 148,
                  },
                },
                chunkContentHash: `sha256:${"c".repeat(64)}`,
                contentRole: "source",
                derivedFromChunkIds: null,
                kind: "edge",
                edge: {
                  edgeId: "e5",
                  graphVersion: "capture-v1",
                  subject: {
                    nodeId: "node-disclosure",
                    label: "Health disclosure",
                  },
                  object: {
                    nodeId: "node-approval",
                    label: "Policy approval",
                  },
                  relationType: "PRECEDES",
                  relationLabel: "precedes",
                },
              },
            ],
          },
        },
      },
    ],
    nextCursor: null,
  },
  // `GET /conversations/{id}/turns/{turnId}/citations/{citationId}` --
  // the historical citation previews for the two edge citations (`e1`,
  // `e5`), fetched lazily on each chip's first hover/focus (Task 8) and
  // again when the evidence panel opens. Keyed by citationId so
  // `ui-capture.spec.ts` can route `.../citations/{id}` to the right one.
  citations: {
    e1: {
      citationId: "e1",
      documentId: CAPTURE_SOURCE_GUIDE.documentId,
      revisionId: CAPTURE_SOURCE_GUIDE.documentRevisionId,
      filename: CAPTURE_SOURCE_GUIDE.filename,
      sourceContentHash: `sha256:${"a".repeat(64)}`,
      chunkContentHash: `sha256:${"b".repeat(64)}`,
      anchor: {
        type: "document",
        headingPath: ["Health disclosure"],
        page: 1,
        bbox: null,
        startOffset: 0,
        endOffset: 72,
      },
      prefix: "",
      quote:
        "Health disclosure must be completed before underwriting review proceeds.",
      suffix: "",
    },
    e5: {
      citationId: "e5",
      documentId: CAPTURE_SOURCE_GUIDE.documentId,
      revisionId: CAPTURE_SOURCE_GUIDE.documentRevisionId,
      filename: CAPTURE_SOURCE_GUIDE.filename,
      sourceContentHash: `sha256:${"a".repeat(64)}`,
      chunkContentHash: `sha256:${"c".repeat(64)}`,
      anchor: {
        type: "document",
        headingPath: ["Policy approval"],
        page: 1,
        bbox: null,
        startOffset: 72,
        endOffset: 148,
      },
      prefix: "",
      quote:
        "Policy approval follows once a disclosure is verified by underwriting review.",
      suffix: "",
    },
  },
};
